SELECT COUNT(*) FROM CITY WHERE DISTRICT='KARNATAKA';
SELECT MAX(POPULATION) FROM CITY WHERE DISTRICT='KARNATAKA';
SELECT * FROM CITY WHERE DISTRICT="KARNATAKA" ORDER BY POPULATION DESC LIMIT 1;
SELECT MIN(NAME) FROM CITY WHERE DISTRICT="KARNATAKA";
SELECT AVG(NAME) FROM CITY WHERE DISTRICT="KARNATAKA"; 
SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT="KARNATAKA"; 